### PR TITLE
Bump Spring Boot/Cloud versions

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@gytis @pavolloffay I don't see why the tests would be failing, do you have any ideas?

**Comment by gytis** [comment]
Just guessing, but there might be a mismatch between Spring Cloud version in here and the one used in the Artemis binder

**Comment by geoand** [comment]
Interesting... We'll probably have to deal with that sooner or later since we need to support this module actively (and probably use Spring Boot `1.5.12` as well)

**Comment by gytis** [comment]
I'll test it locally later today

**Comment by geoand** [comment]
Cool, thanks!

**Comment by gytis** [comment]
I was right with the suspicion. The issue is with the mismatch of the spring cloud stream version introduced by the spring cloud dependencies version change. Even though in this case this is only a test problem and doesn't influence the functionality of this project, I suggest to upgrade the Artemis binder.

How urgently do you need to merge this pull request?

**Comment by gytis** [comment]
Just to be clear, I've fixed the issue locally by aligning versions. Now it's the matter of making sure everything is in line and then releasing the new version of the binder, which could then be incorporated to this PR.

**Comment by gytis** [comment]
I've released a new version for the Spring Cloud Stream Artemis binder, which would fix this failure. I'll update you're PR once it's synced with Maven Central

**Comment by pavolloffay** [comment]
Any update on this? Can we use SB 2.x?

**Comment by pavolloffay** [comment]
the spring cloud has been released for SB 2.x. Which includes a dependency on this project. We should also bump this one.

If this is done could you please merge and cut a new version?

**Comment by geoand** [comment]
@gytis Do you have any idea?

Otherwise I need to look into it

**Comment by gytis** [comment]
I'll release the latest Artemis binder version which works with SB 2 and update this PR

**Comment by geoand** [comment]
Thank you @gytis !

**Comment by gytis** [comment]
@geoand you were offline and there were a few changes that had to be done, so I'll raised a new PR https://github.com/opentracing-contrib/java-spring-messaging/pull/21. Feel free to cherry-pick the commit to this PR or just close this and review the new one.

**Comment by geoand** [comment]
Thanks @gytis! 
I was at a Kubernetes meetup so had to take off early :) 

I'll check out the PR

**Comment by geoand** [comment]
@gytis @pavolloffay I think we can close this favor of #21, WDYT?

**Comment by gytis** [comment]
+1

**Pull request closed without merging**
