### PR TITLE
Use license date from git history

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by pavolloffay** [comment]
I will merge and cut the first release `0.1.0`

**Comment by gytis** [comment]
Sorry just noticed your message. Thanks for releasing, I doubt that I have permissions for that.

**Comment by pavolloffay** [comment]
You should be able to release it too. You just need push permissions to this repo. Release process is just to push a tag see the readme. 

It's released and synced with JCenter, it might take some time to propagate to central. Usually it's an hour or so.

**Comment by gytis** [comment]
OK I can do the next release then.

**Pull request merged**
